[project]
name = "cli-llm"
version = "0.1.0"
description = "A LLM running on a CLI, offering seamless features."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pre-commit>=4.2.0",
    "ruff>=0.11.7",
]
